<?php

return [
    'name' => 'Veltrix',
    'author' => 'QKing and Melvin',
    'url' => 'https://veltrix.freemchosting.com',

    'settings' => [
        [
            'name' => 'hidelogotext', 
            'label' => 'Hide company name in navbar', 
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Don\'t show the company name on the right of the logo in the navbar', 
        ],
        [
            'name' => 'direct_checkout',
            'label' => 'Direct Checkout',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Don\'t show the product overview page, go directly to the checkout page',
        ],
        [
            'name' => 'descript',
            'label' => 'Product Desciption', 
            'type' => 'checkbox',
            'default' => false,
            'description' => 'description in product',
        ],
        [
            'name' => 'cookie',
            'label' => 'Cookie Consent', 
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Cookie consent banner',
        ],
        [
            'name' => 'small_images',
            'label' => 'Small Images',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Show small images in the product overview page',
        ],
        [
            'name' => 'level', 
            'label' => 'Level Images', 
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Level the images to keep text on same height', 
        ],
        [
            'name' => 'show_category_description',
            'label' => 'Show Category Description',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Show the category description in the product overview page/homepage',
        ],
        [
            'name' => 'home_page_text',
            'label' => 'Home Page Text',
            'type' => 'markdown',
            'default' => 'Welcome to Paymenter!',
        ],
        [
            'name' => 'description',
            'label' => 'Description Style',
            'type' => 'select',
            'default' => 'default',
            'options' => [
                'default' => 'Default Home Page Text',
                'no-border'=> 'No-Border Home Page Text',
            ],
            'description' => 'Select the style of the Home Page Text',
        ],
        [
            'name' => 'Discord-link',
            'label' => 'Discord Invite Link',
            'type' => 'text',
            'default' => 'https://discord.com/invite/x3s5juS7EH',
        ],
        [
            'name' => 'Home-link',
            'label' => 'Home Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com',
        ],
        [
            'name' => 'Feature-link',
            'label' => 'Feature Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/#features',
        ],
        [
            'name' => 'Pricing-link',
            'label' => 'Pricing Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/#compare',
        ],
        [
            'name' => 'Contact-link',
            'label' => 'Contact Support Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/contact',
        ],
        [
            'name' => 'Status-link',
            'label' => 'Status Link',
            'type' => 'text',
            'default' => 'https://status.freemchosting.com/status/freemchosting',
        ],
        [
            'name' => 'About-link',
            'label' => 'About Us Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/aboutus',
        ],
        [
            'name' => 'Privacy-policy-link',
            'label' => 'Privacy Policy Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/privacy-policy',
        ],
        [
            'name' => 'Tos-link',
            'label' => 'Terms of Service Link',
            'type' => 'text',
            'default' => 'https://freemchosting.com/terms-of-service',
        ],
        [
            'name' => 'primary',
            'label' => 'Primary - Button Color',
            'type' => 'color',
            'default' => 'hsl(229, 100%, 64%)',
        ],
        [
            'name' => 'secondary',
            'label' => 'Secondary - Button Color',
            'type' => 'color',
            'default' => 'hsl(237, 33%, 60%)',
        ],
        [
            'name' => 'neutral',
            'label' => 'Borders, Accents... (Light)',
            'type' => 'color',
            'default' => 'hsl(220, 25%, 85%)',
        ],
        [
            'name' => 'base',
            'label' => 'Base - Text Color (Light)',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 0%)',
        ],
        [
            'name' => 'muted',
            'label' => 'Muted - Text Color (Light)',
            'type' => 'color',
            'default' => 'hsl(220, 28%, 25%)',
        ],
        [
            'name' => 'inverted',
            'label' => 'Inverted - Text Color (Light)',
            'type' => 'color',
            'default' => 'hsl(100, 100%, 100%)',
        ],
        [
            'name' => 'background',
            'label' => 'Background - Color (Light)',
            'type' => 'color',
            'default' => 'hsl(100, 100%, 100%)',
        ],
        [
            'name' => 'background-secondary',
            'label' => 'Background - Secondary Color (Light)',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 97%)',
        ],
        [
            'name' => 'dark-primary',
            'label' => 'Primary - Brand Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(229, 100%, 64%)',
        ],
        [
            'name' => 'dark-secondary',
            'label' => 'Secondary - Brand Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(237, 33%, 60%)',
        ],
        [
            'name' => 'dark-neutral',
            'label' => 'Borders, Accents... (Dark)',
            'type' => 'color',
            'default' => 'hsl(220, 25%, 29%)',
        ],
        [
            'name' => 'dark-base',
            'label' => 'Base - Text Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(100, 100%, 100%)',
        ],
        [
            'name' => 'dark-muted',
            'label' => 'Muted - Text Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(220, 28%, 25%)',
        ],
        [
            'name' => 'dark-inverted',
            'label' => 'Inverted - Text Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(220, 14%, 60%)',
        ],
        [
            'name' => 'dark-background',
            'label' => 'Background - Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(221, 39%, 11%)',
        ],
        [
            'name' => 'dark-background-secondary',
            'label' => 'Background - Secondary Color (Dark)',
            'type' => 'color',
            'default' => 'hsl(217, 33%, 16%)',
        ],
        [
        'name' => 'html',
        'label' => 'Custom HTML Embed',
        'type' => 'textarea',
        'default' => '<div class="bg-blue-500/10 p-4 rounded-lg">
            <p class="text-blue-500">Default HTML Content</p>
        </div>',
        'attributes' => [
            'rows' => 5,
        ],
        'sanitize' => false, // Allows HTML to be rendered or otherwise some bad shit will happen - QKing
        ],
        [
        'name' => 'htmltitle',
        'label' => 'Custom Embed Title',
        'type' => 'text',
        'default' => 'Custom Content',
        'attributes' => [
        'placeholder' => 'Enter widget title here'
        ],
        ],
        [
        'name' => 'icon', //I'm regretting this - QKing
        'label' => 'Icon',
        'type' => 'select',
        'default' => 'document',
        'options' => [
        'add-circle' => 'Add Circle',
        'admin' => 'Admin',
        'airplay' => 'Airplay',
        'alarm' => 'Alarm',
        'alert' => 'Alert',
        'alert-circle' => 'Alert Circle',
        'apps' => 'Apps',
        'arrow-down' => 'Arrow Down',
        'arrow-left' => 'Arrow Left',
        'arrow-right' => 'Arrow Right',
        'arrow-up' => 'Arrow Up',
        'sort-asc' => 'Sort Ascending',
        'attachment' => 'Attachment',
        'bar-chart' => 'Bar Chart',
        'barcode' => 'Barcode',
        'battery' => 'Battery',
        'battery-charge' => 'Battery Charge',
        'battery-low' => 'Battery Low',
        'bell' => 'Bell',
        'bluetooth' => 'Bluetooth',
        'bluetooth-connect' => 'Bluetooth Connect',
        'book' => 'Book',
        'bookmark' => 'Bookmark',
        'git-branch' => 'Git Branch',
        'brush' => 'Brush',
        'bug' => 'Bug',
        'cpu' => 'CPU',
        'calendar' => 'Calendar',
        'calendar-check' => 'Calendar Check',
        'calendar-event' => 'Calendar Event',
        'camera' => 'Camera',
        'camera-off' => 'Camera Off',
        'cast' => 'Cast',
        'file-chart' => 'File Chart',
        'chart' => 'Chart',
        'check' => 'Check',
        'check-circle' => 'Check Circle',
        'shopping-cart' => 'Shopping Cart',
        'chat' => 'Chat',
        'add-circle' => 'Add Circle',
        'alert-circle' => 'Alert Circle',
        'check-circle' => 'Check Circle',
        'close-circle' => 'Close Circle',
        'pause-circle' => 'Pause Circle',
        'play-circle' => 'Play Circle',
        'record-circle' => 'Record Circle',
        'stop-circle' => 'Stop Circle',
        'time-circle' => 'Time Circle',
        'zoom-in-circle' => 'Zoom In Circle',
        'zoom-out-circle' => 'Zoom Out Circle',
        'cloud' => 'Cloud',
        'download-cloud' => 'Download Cloud',
        'upload-cloud' => 'Upload Cloud',
        'code' => 'Code',
        'file-code' => 'File Code',
        'qrcode' => 'QR Code',
        'git-commit' => 'Git Commit',
        'command' => 'Command',
        'compass' => 'Compass',
        'bluetooth-connect' => 'Bluetooth Connect',
        'contrast' => 'Contrast',
        'file-copy' => 'File Copy',
        'credit-card' => 'Credit Card',
        'dashboard' => 'Dashboard',
        'database' => 'Database',
        'delete' => 'Delete',
        'sort-desc' => 'Sort Descending',
        'document' => 'Document',
        'download' => 'Download',
        'file-download' => 'File Download',
        'cloud-download' => 'Cloud Download',
        'volume-down' => 'Volume Down',
        'thumb-down' => 'Thumb Down',
        'zoom-out' => 'Zoom Out',
        'hard-drive' => 'Hard Drive',
        'drop' => 'Drop',
        'edit' => 'Edit',
        'file-edit' => 'File Edit',
        'error' => 'Error',
        'calendar-event' => 'Calendar Event',
        'file-excel' => 'File Excel',
        'external-link' => 'External Link',
        'eye' => 'Eye',
        'file' => 'File',
        'file-add' => 'File Add',
        'file-chart' => 'File Chart',
        'file-code' => 'File Code',
        'file-copy' => 'File Copy',
        'file-download' => 'File Download',
        'file-edit' => 'File Edit',
        'file-excel' => 'File Excel',
        'file-image' => 'File Image',
        'file-list' => 'File List',
        'file-lock' => 'File Lock',
        'file-music' => 'File Music',
        'file-pdf' => 'File PDF',
        'file-search' => 'File Search',
        'file-settings' => 'File Settings',
        'file-shield' => 'File Shield',
        'file-upload' => 'File Upload',
        'file-user' => 'File User',
        'file-video' => 'File Video',
        'file-warning' => 'File Warning',
        'file-word' => 'File Word',
        'file-zip' => 'File Zip',
        'filter' => 'Filter',
        'fingerprint' => 'Fingerprint',
        'fire' => 'Fire',
        'flag' => 'Flag',
        'flashlight' => 'Flashlight',
        'flask' => 'Flask',
        'user-follow' => 'User Follow',
        'folder' => 'Folder',
        'folder-add' => 'Folder Add',
        'folder-lock' => 'Folder Lock',
        'forbid' => 'Forbid',
        'forbid-2' => 'Forbid 2',
        'fullscreen' => 'Fullscreen',
        'function' => 'Function',
        'game' => 'Game',
        'settings-gear' => 'Settings Gear',
        'gift' => 'Gift',
        'global' => 'Global',
        'grid' => 'Grid',
        'group' => 'Group',
        'hashtag' => 'Hashtag',
        'heart' => 'Heart',
        'user-heart' => 'User Heart',
        'headphone' => 'Headphone',
        'history' => 'History',
        'home' => 'Home',
        'hourglass' => 'Hourglass',
        'file-image' => 'File Image',
        'zoom-in' => 'Zoom In',
        'inbox' => 'Inbox',
        'info' => 'Info',
        'information' => 'Information',
        'key' => 'Key',
        'keyboard' => 'Keyboard',
        'layout' => 'Layout',
        'arrow-left' => 'Arrow Left',
        'lightbulb' => 'Lightbulb',
        'line-chart' => 'Line Chart',
        'link' => 'Link',
        'external-link' => 'External Link',
        'file-list' => 'File List',
        'loader' => 'Loader',
        'user-location' => 'User Location',
        'lock' => 'Lock',
        'file-lock' => 'File Lock',
        'folder-lock' => 'Folder Lock',
        'login' => 'Login',
        'logout' => 'Logout',
        'battery-low' => 'Battery Low',
        'magic' => 'Magic',
        'mail' => 'Mail',
        'mail-open' => 'Mail Open',
        'mail-unread' => 'Mail Unread',
        'map' => 'Map',
        'map-pin' => 'Map Pin',
        'menu' => 'Menu',
        'git-merge' => 'Git Merge',
        'microphone' => 'Microphone',
        'money' => 'Money',
        'moon' => 'Moon',
        'more' => 'More',
        'mouse' => 'Mouse',
        'movie' => 'Movie',
        'music' => 'Music',
        'file-music' => 'File Music',
        'navigation' => 'Navigation',
        'newspaper' => 'Newspaper',
        'sticky-note' => 'Sticky Note',
        'notification' => 'Notification',
        'eye-off' => 'Eye Off',
        'camera-off' => 'Camera Off',
        'microphone-off' => 'Microphone Off',
        'volume-off' => 'Volume Off',
        'wifi-off' => 'Wifi Off',
        'mail-open' => 'Mail Open',
        'zoom-out' => 'Zoom Out',
        'package' => 'Package',
        'paint' => 'Paint',
        'palette' => 'Palette',
        'file-pdf' => 'File PDF',
        'phone' => 'Phone',
        'pie-chart' => 'Pie Chart',
        'map-pin' => 'Map Pin',
        'play-circle' => 'Play Circle',
        'printer' => 'Printer',
        'git-pull-request' => 'Git Pull Request',
        'question' => 'Question',
        'user-received' => 'User Received',
        'record-circle' => 'Record Circle',
        'refresh' => 'Refresh',
        'reply' => 'Reply',
        'git-repository' => 'Git Repository',
        'restart' => 'Restart',
        'arrow-right' => 'Arrow Right',
        'rocket' => 'Rocket',
        'router' => 'Router',
        'ruler' => 'Ruler',
        'save' => 'Save',
        'scan' => 'Scan',
        'search' => 'Search',
        'file-search' => 'File Search',
        'user-search' => 'User Search',
        'send' => 'Send',
        'settings' => 'Settings',
        'file-settings' => 'File Settings',
        'user-settings' => 'User Settings',
        'share' => 'Share',
        'user-shared' => 'User Shared',
        'shield' => 'Shield',
        'file-shield' => 'File Shield',
        'shut-down' => 'Shut Down',
        'sidebar' => 'Sidebar',
        'smartphone' => 'Smartphone',
        'stack' => 'Stack',
        'star' => 'Star',
        'user-add' => 'User Add',
        'user-star' => 'User Star',
        'stop-circle' => 'Stop Circle',
        'store' => 'Store',
        'subtract' => 'Subtract',
        'sun' => 'Sun',
        'table' => 'Table',
        'tablet' => 'Tablet',
        'price-tag' => 'Price Tag',
        'team' => 'Team',
        'terminal' => 'Terminal',
        'text' => 'Text',
        'thumb-down' => 'Thumb Down',
        'thumb-up' => 'Thumb Up',
        'time' => 'Time',
        'timer' => 'Timer',
        'translate' => 'Translate',
        'truck' => 'Truck',
        'tv' => 'TV',
        'umbrella' => 'Umbrella',
        'underline' => 'Underline',
        'user-unfollow' => 'User Unfollow',
        'unlock' => 'Unlock',
        'mail-unread' => 'Mail Unread',
        'arrow-up' => 'Arrow Up',
        'thumb-up' => 'Thumb Up',
        'volume-up' => 'Volume Up',
        'zoom-in' => 'Zoom In',
        'upload' => 'Upload',
        'file-upload' => 'File Upload',
        'cloud-upload' => 'Cloud Upload',
        'user' => 'User',
        'file-user' => 'File User',
        'file-video' => 'File Video',
        'wallet' => 'Wallet',
        'file-warning' => 'File Warning',
        'wifi' => 'Wifi',
        'wind' => 'Wind',
        'window' => 'Window',
        'file-word' => 'File Word',
        'file-zip' => 'File Zip'
        ],
        'attributes' => [
        'class' => 'w-full',
        ],
        ],
        [
        'name' => 'footerbutton',
        'label' => 'Footer Button Text',
        'type' => 'text',
        'default' => 'View More',
        ],
        [
        'name' => 'footerlink',
        'label' => 'Footer Button Link',
        'type' => 'text',
        'default' => '#',
        ],
        [
        'name' => 'title1',
        'label' => 'Feature 1 Title',
        'type' => 'text',
        'default' => 'Free Credits',
        'attributes' => [
        'placeholder' => 'Enter title for Feature 1'
        ],
        ],
        [
        'name' => 'content1',
        'label' => 'Feature 1 HTML Content',
        'type' => 'textarea',
        'default' => '<div class="bg-indigo-500/10 p-4 rounded-lg">
            <p class="text-indigo-500">Earn credits through our rewards system and access all services without spending real money.</p>
        </div>',
        'attributes' => [
            'rows' => 5,
        ],
        'sanitize' => false,
        ],
        [
        'name' => 'title2',
        'label' => 'Feature 2 Title',
        'type' => 'text',
        'default' => 'VIP Benefits',
        'attributes' => [
            'placeholder' => 'Enter title for Feature 2'
        ],
        ],
        [
        'name' => 'content2',
        'label' => 'Feature 2 HTML Content',
        'type' => 'textarea',
        'default' => '<div class="bg-purple-500/10 p-4 rounded-lg">
            <p class="text-purple-500">Upgrade to VIP for premium features, priority support, and exclusive resources.</p>
        </div>',
        'attributes' => [
            'rows' => 5,
        ],
        'sanitize' => false,
        ],
        [
        'name' => 'title3',
        'label' => 'Feature 3 Title',
        'type' => 'text',
        'default' => 'Secure & Reliable',
        'attributes' => [
            'placeholder' => 'Enter title for Feature 3'
        ],
        ],
        [
        'name' => 'content3',
        'label' => 'Feature 3 HTML Content',
        'type' => 'textarea',
        'default' => '<div class="bg-green-500/10 p-4 rounded-lg">
            <p class="text-green-500">Enterprise-grade security and 99.9% uptime guarantee for all your hosting needs.</p>
        </div>',
        'attributes' => [
            'rows' => 5,
        ],
        'sanitize' => false,
        ],
        [
            'name' => 'iconbg1',
            'label' => 'Icon Background 1',
            'type' => 'color',
            'default' => 'hsl(217, 91%, 60%)',
        ],
        [
            'name' => 'iconbg2',
            'label' => 'Icon Background 2',
            'type' => 'color',
            'default' => 'hsl(142, 76%, 36%)',
        ],
        [
            'name' => 'iconbg3',
            'label' => 'Icon Background 3',
            'type' => 'color',
            'default' => 'hsl(346, 87%, 43%)',
        ],
        [
            'name' => 'icon1',
            'label' => 'Icon Color 1',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'icon2',
            'label' => 'Icon Color 2',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'icon3',
            'label' => 'Icon Color 3',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'dark-iconbg1',
            'label' => 'Icon Background 1 (Dark)',
            'type' => 'color',
            'default' => 'hsl(217, 91%, 60%)',
        ],
        [
            'name' => 'dark-iconbg2',
            'label' => 'Icon Background 2 (Dark)',
            'type' => 'color',
            'default' => 'hsl(142, 76%, 36%)',
        ],
        [
            'name' => 'dark-iconbg3',
            'label' => 'Icon Background 3 (Dark)',
            'type' => 'color',
            'default' => 'hsl(346, 87%, 43%)',
        ],
        [
            'name' => 'dark-icon1',
            'label' => 'Icon Color 1 (Dark)',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'dark-icon2',
            'label' => 'Icon Color 2 (Dark)',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'dark-icon3',
            'label' => 'Icon Color 3 (Dark)',
            'type' => 'color',
            'default' => 'hsl(0, 0%, 100%)',
        ],
        [
            'name' => 'hero_heading_line1',
            'label' => 'Hero Heading Line 1',
            'type' => 'text',
            'default' => 'Elevate Your',
        ],
        [
            'name' => 'hero_heading_line2',
            'label' => 'Hero Heading Line 2',
            'type' => 'text',
            'default' => 'Digital Experience',
        ],
        [
            'name' => 'hero_paragraph',
            'label' => 'Hero Paragraph Text',
            'type' => 'text',
            'default' => 'Streamline your workflow with our premium hosting platform. Everything you need in one unified dashboard.',
        ],



        [
            'name' => 'register_title',
            'label' => 'Registration Title',
            'type' => 'text',
            'default' => 'Create Your Account',
        ],
        [
            'name' => 'register_subtitle',
            'label' => 'Registration Subtitle',
            'type' => 'text',
            'default' => 'Join our community today',
        ],
        [
            'name' => 'lhero_heading_line1',
            'label' => 'Hero Heading Line 1 Registration',
            'type' => 'text',
            'default' => 'Start Your Journey',
        ],
        [
            'name' => 'lhero_heading_line2',
            'label' => 'Hero Heading Line 2 Registration',
            'type' => 'text',
            'default' => 'With Us',
        ],
        [
            'name' => 'lhero_paragraph',
            'label' => 'Hero Paragraph Text Registration',
            'type' => 'text',
            'default' => 'Join thousands of satisfied users who trust our platform for their needs. Get started in just a few clicks.',
        ],
        [
            'name' => 'lfeature_1',
            'label' => 'Feature 1 Text',
            'type' => 'text',
            'default' => 'Premium features at no extra cost',
        ],
        [
            'name' => 'lfeature_2',
            'label' => 'Feature 2 Text',
            'type' => 'text',
            'default' => '24/7 customer support',
        ],
        [
            'name' => 'lfeature_3',
            'label' => 'Feature 3 Text',
            'type' => 'text',
            'default' => 'Secure and reliable platform',
        ],
        [
            'name' => 'register_button_text',
            'label' => 'Registration Button Text',
            'type' => 'text',
            'default' => 'Sign up',
        ],
        [
            'name' => 'login_link_text',
            'label' => 'Login Link Text',
            'type' => 'text',
            'default' => 'Already have an account?',
        ],
        [
            'name' => 'login_link_button',
            'label' => 'Login Link Button Text',
            'type' => 'text',
            'default' => 'Sign in',
        ],
        [
            'name' => 'inject',
            'label' => 'Custom Head Injection',
            'type' => 'textarea',
            'description' => 'Add custom scripts, analytics, or monitoring code here. Will be injected into the head section.',
            'default' => '',
            'placeholder' => '<script>console.log("Custom injection working!");</script>',
        ],

        [
            'name' => 'enable_google_analytics',
            'label' => 'Enable Google Analytics',
            'type' => 'checkbox',
            'default' => false,
        ],

        [
            'name' => 'google_analytics_id',
            'label' => 'Google Analytics Tracking ID',
            'type' => 'text',
            'default' => '',
            'placeholder' => 'e.g. UA-12345678-1',
            'dependency' => ['enable_google_analytics' => true],  // show only if enabled
        ],
        [
            'name' => 'enable_custom_script',
            'label' => 'Enable Custom Script',
            'type' => 'checkbox',
            'default' => false,
        ],
        [
            'name' => 'custom_script_code',
            'label' => 'Custom Script Code',
            'type' => 'textarea',
            'default' => '',
            'placeholder' => '<script>console.log("Custom injection working!");</script>',
            'dependency' => ['enable_custom_script' => true],  // show only if enabled
        ],

        // Basic SEO
        ['name' => 'seo_title', 'label' => 'SEO Title', 'type' => 'text', 'default' => '', 'placeholder' => 'Site Title'],
        ['name' => 'seo_description', 'label' => 'Meta Description', 'type' => 'textarea', 'default' => '', 'placeholder' => 'Short description for search engines'],
        ['name' => 'seo_keywords', 'label' => 'Meta Keywords', 'type' => 'text', 'default' => '', 'placeholder' => 'keyword1, keyword2, keyword3'],
        
        // Open Graph
        ['name' => 'og_title', 'label' => 'OG Title', 'type' => 'text', 'default' => '', 'placeholder' => 'Title shown in social shares'],
        ['name' => 'og_description', 'label' => 'OG Description', 'type' => 'textarea', 'default' => '', 'placeholder' => 'Description shown in social shares'],
        ['name' => 'og_image', 'label' => 'OG Image URL', 'type' => 'text', 'default' => '', 'placeholder' => 'https://...'],

        // Twitter Card
        ['name' => 'twitter_card', 'label' => 'Twitter Card Type', 'type' => 'text', 'default' => 'summary_large_image', 'placeholder' => 'summary or summary_large_image'],
        ['name' => 'twitter_site', 'label' => 'Twitter @username', 'type' => 'text', 'default' => '', 'placeholder' => '@yoursite'],
        ['name' => 'twitter_image', 'label' => 'Twitter Image URL', 'type' => 'text', 'default' => '', 'placeholder' => 'https://...'],

        // Canonical URL
        ['name' => 'canonical_url', 'label' => 'Canonical URL', 'type' => 'text', 'default' => '', 'placeholder' => 'https://...'],

        // Robots
        ['name' => 'robots_content', 'label' => 'Robots Meta Content', 'type' => 'text', 'default' => 'index, follow', 'placeholder' => 'index, follow / noindex, nofollow'],



        //Customisation extra (probably for v3 or enterprise)
        [
            'name' => 'header_style',
            'label' => 'Header Style',
            'type' => 'select',
            'default' => 'default',
            'options' => [
                'default' => 'Default Header',
                'centered' => 'Centered Header',
                'minimal' => 'Minimal Header',
                'custom' => 'Custom Header'
            ],
            'description' => 'Select the style of the header section',
        ],
        [
            'name' => 'custom_header',
            'label' => 'Custom Header',
            'type' => 'textarea',
            'default' => '',
            'placeholder' => 'HTML content for custom header',
        ],
        [
            'name' => 'footer_style',
            'label' => 'Footer Style',
            'type' => 'select',
            'default' => 'default',
            'options' => [
                'default' => 'Default Footer',
                'simple' => 'Simple Footer',
                'expanded' => 'Expanded Footer',
                'none' => 'No Footer',
                'custom' => 'Custom Footer'
            ],
            'description' => 'Select the style of the footer section',
        ],
        [
            'name' => 'footer_tagline',
            'label' => 'Footer Tagline',
            'type' => 'text',
            'default' => 'Modern solutions for modern businesses.',
            'placeholder' => 'The text on the left side of the footer',
        ],
        [
            'name' => 'custom_footer',
            'label' => 'Custom Footer',
            'type' => 'textarea',
            'default' => '',
            'placeholder' => 'HTML content for custom footer',
        ],
        [
            'name' => 'custom_layout_css',
            'label' => 'Custom Layout CSS',
            'type' => 'textarea',
            'default' => '',
            'placeholder' => '/* Add your custom layout CSS here */',
            'description' => 'Add custom CSS for layout customization',
            'dependency' => ['layout_type' => 'custom'],
        ],
        [
            'name' => 'enable_smooth_scroll',
            'label' => 'Enable Smooth Scrolling',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable smooth scrolling behavior',
        ],
        [
            'name' => 'show_scroll_to_top',
            'label' => 'Show Scroll to Top Button',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Display a button to scroll back to top',
        ],
        [
            'name' => 'lazy_loading_enabled',
            'label' => 'Enable Lazy Loading',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable automatic lazy loading for images, backgrounds, and iframes',
        ],
        [
            'name' => 'lazy_root_margin',
            'label' => 'Lazy Loading Root Margin',
            'type' => 'text',
            'default' => '500px 0px',
            'description' => 'How far ahead to start loading content (e.g., "500px 0px" for very aggressive pre-loading)',
        ],
        [
            'name' => 'lazy_threshold',
            'label' => 'Intersection Threshold',
            'type' => 'number',
            'default' => 0.001,
            'step' => 0.001,
            'min' => 0,
            'max' => 1,
            'description' => 'Threshold for when to trigger lazy loading (0.001 = very early)',
        ],
        [
            'name' => 'lazy_delay',
            'label' => 'Initial Delay (ms)',
            'type' => 'number',
            'default' => 50,
            'min' => 0,
            'max' => 5000,
            'description' => 'Delay before initializing lazy loading in milliseconds',
        ],
        [
            'name' => 'lazy_recheck_delay',
            'label' => 'Recheck Delay (ms)',
            'type' => 'number',
            'default' => 500,
            'min' => 100,
            'max' => 2000,
            'description' => 'Delay before rechecking for new lazy load items in milliseconds',
        ],
        [
            'name' => 'lazy_timeout',
            'label' => 'Loading Timeout (ms)',
            'type' => 'number',
            'default' => 100,
            'min' => 50,
            'max' => 1000,
            'description' => 'Timeout for loading individual items in milliseconds',
        ],

        // === CSS Classes ===
        [
            'name' => 'lazy_class',
            'label' => 'Lazy Loading Class',
            'type' => 'text',
            'default' => 'lazy-auto',
            'description' => 'CSS class applied to elements waiting to be loaded',
        ],
        [
            'name' => 'lazy_loaded_class',
            'label' => 'Loaded Class',
            'type' => 'text',
            'default' => 'lazy-loaded',
            'description' => 'CSS class applied to successfully loaded elements',
        ],
        [
            'name' => 'lazy_loading_class',
            'label' => 'Loading Class',
            'type' => 'text',
            'default' => 'lazy-loading',
            'description' => 'CSS class applied while elements are being loaded',
        ],
        [
            'name' => 'lazy_error_class',
            'label' => 'Error Class',
            'type' => 'text',
            'default' => 'lazy-error',
            'description' => 'CSS class applied when loading fails',
        ],

        // === Element Selectors ===
        [
            'name' => 'lazy_images_enabled',
            'label' => 'Lazy Load Images',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable lazy loading for images',
        ],
        [
            'name' => 'lazy_backgrounds_enabled',
            'label' => 'Lazy Load Background Images',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable lazy loading for background images',
        ],
        [
            'name' => 'lazy_iframes_enabled',
            'label' => 'Lazy Load iFrames',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Enable lazy loading for iframes (embeds, videos)',
        ],
        [
            'name' => 'lazy_custom_selector',
            'label' => 'Custom Element Selector',
            'type' => 'text',
            'default' => '',
            'description' => 'Additional CSS selector for custom elements to lazy load (optional)',
        ],

        // === Performance Settings ===
        [
            'name' => 'lazy_throttle_limit',
            'label' => 'Scroll Throttle Limit (ms)',
            'type' => 'number',
            'default' => 100,
            'min' => 50,
            'max' => 500,
            'description' => 'Throttle limit for scroll events (fallback for older browsers)',
        ],
        [
            'name' => 'lazy_viewport_multiplier',
            'label' => 'Viewport Size Multiplier',
            'type' => 'number',
            'default' => 2,
            'min' => 1,
            'max' => 5,
            'step' => 0.5,
            'description' => 'Multiplier for viewport size when checking visibility (fallback)',
        ],
        [
            'name' => 'lazy_use_idle_callback',
            'label' => 'Use Idle Callback',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Use requestIdleCallback for better performance (modern browsers)',
        ],

        // === Dynamic Content Support ===
        [
            'name' => 'lazy_observe_dom',
            'label' => 'Observe DOM Changes',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Automatically handle dynamically added content (AJAX, Livewire, etc.)',
        ],
        [
            'name' => 'lazy_mutation_delay',
            'label' => 'DOM Mutation Delay (ms)',
            'type' => 'number',
            'default' => 100,
            'min' => 50,
            'max' => 1000,
            'description' => 'Delay after DOM changes before checking for new lazy load items',
        ],

        // === Advanced Options ===
        [
            'name' => 'lazy_fallback_enabled',
            'label' => 'Enable Fallback for Old Browsers',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Provide scroll-based fallback for browsers without IntersectionObserver',
        ],
        [
            'name' => 'lazy_events_enabled',
            'label' => 'Dispatch Custom Events',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Dispatch "lazy-loaded" events for integration with other scripts',
        ],
        [
            'name' => 'lazy_console_errors',
            'label' => 'Log Console Errors',
            'type' => 'checkbox',
            'default' => true,
            'description' => 'Log lazy loading errors to browser console for debugging',
        ],
        [
            'name' => 'lazy_ignore_attribute',
            'label' => 'Ignore Attribute',
            'type' => 'text',
            'default' => 'data-lazy-ignore',
            'description' => 'Attribute to mark elements/containers to exclude from lazy loading',
        ],

        // === Critical Content Exclusions ===
        [
            'name' => 'lazy_critical_selectors',
            'label' => 'Critical Content Selectors',
            'type' => 'textarea',
            'default' => 'header, .hero, .above-fold, .critical',
            'description' => 'CSS selectors for critical content that should never be lazy loaded (comma-separated)',
        ],
        [
            'name' => 'lazy_skip_small_images',
            'label' => 'Skip Small Images',
            'type' => 'checkbox',
            'default' => false,
            'description' => 'Skip lazy loading for small images (icons, thumbnails)',
        ],
        [
            'name' => 'lazy_small_image_threshold',
            'label' => 'Small Image Threshold (px)',
            'type' => 'number',
            'default' => 50,
            'min' => 10,
            'max' => 200,
            'description' => 'Maximum size in pixels to consider an image "small"',
        ],
    ],
    
];
