version: "3.8"

x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "${MYSQL_PASSWORD}"
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

services:
  database:
    image: mariadb:lts
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "paymenter"
      MYSQL_USER: "paymenter"

  cache:
    image: redis:alpine
    restart: always

  paymenter:
    # Replaced 'image:' with 'build:' to use our custom Dockerfile
    build: .
    restart: always
    ports:
      - "${PAYMENTER_PORT}:80"
    links:
      - database
      - cache
    volumes:
      # These are more specific, safer volume mounts
      - "./config:/app/var"
      - "./storage/logs:/app/storage/logs"
      - "./storage/app/public:/app/storage/app/public"
    environment:
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      APP_ENV: "${APP_ENV:-production}"
      CACHE_STORE: "redis"
      REDIS_HOST: "cache"
      DB_CONNECTION: "mariadb"
      DB_HOST: "database"
      DB_PORT: "3306"