version: "3.8"

x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "${MYSQL_PASSWORD}"
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

services:
  database:
    image: mariadb:lts
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"

  cache:
    image: redis:alpine
    restart: always

  paymenter:
    image: ghcr.io/paymenter/paymenter:latest
    restart: always
    ports:
      - "80:80"
    links:
      - database
      - cache
    volumes:
      - "./:/app/var/"
      - "./storage/logs:/app/storage/logs"
      - "./storage/public:/app/storage/app/public"
    environment:
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      APP_ENV: "${APP_ENV:-production}"
      CACHE_STORE: "redis"
      REDIS_HOST: "cache"
      DB_CONNECTION: "mariadb"
      DB_HOST: "database"
      DB_PORT: "3306"
